### ISSUE TITLE
How to Login QR

### ISSUE THREAD

**Issue by CanD62** [nevoit/Automated-Messages#22]
Hi, i'm make projects sent message whatsapp web, use selenium php..
now, i'm already print QR to my web browser at localhost. and then i scan but not reaction form my browser. but on my phone scan successfully.

can you help me to login after scan QR ?

![Untitled](https://user-images.githubusercontent.com/7421087/67148416-7feb8300-f2c9-11e9-8e41-be06e5e861ea.png)

**Comment by ShuratCode** [comment]
Hi, You can look at our code and see how we did it.
But in general you need to log in to whatsapp via the web browser and then scan the code with your phone
